<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="17533" started-at="2019-05-23T15:26:50Z" finished-at="2019-05-23T15:27:08Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="13294" started-at="2019-05-23T15:26:50Z" finished-at="2019-05-23T15:27:04Z">
      <class name="com.hst.testcase.LoginTest">
        <test-method status="FAIL" signature="loginTest1(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.hst.testcase.LoginTest@146ba0ac]" name="loginTest1" duration-ms="13240" started-at="2019-05-23T23:26:50Z" data-provider="login" finished-at="2019-05-23T23:27:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[账号密码正确]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[heshengtao]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[heshengtao]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at com.hst.testcase.LoginTest.loginTest1(LoginTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest1 -->
      </class> <!-- com.hst.testcase.LoginTest -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="4218" started-at="2019-05-23T15:27:04Z" finished-at="2019-05-23T15:27:08Z">
      <class name="com.hst.testcase.LoginTest">
        <test-method status="PASS" signature="start()[pri:0, instance:com.hst.testcase.LoginTest@6fd02e5]" name="start" is-config="true" duration-ms="8930" started-at="2019-05-23T23:26:41Z" finished-at="2019-05-23T23:26:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="loginTest2(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.hst.testcase.LoginTest@6fd02e5]" name="loginTest2" duration-ms="4216" started-at="2019-05-23T23:27:04Z" finished-at="2019-05-23T23:27:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[账号及密码不正确]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[77]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[88]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest2 -->
        <test-method status="PASS" signature="end()[pri:0, instance:com.hst.testcase.LoginTest@6fd02e5]" name="end" is-config="true" duration-ms="3001" started-at="2019-05-23T23:27:08Z" finished-at="2019-05-23T23:27:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- com.hst.testcase.LoginTest -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
